version: "3.9"

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=productsdb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

networks:
  app-network:
    driver: bridge